
export const SHORT_WORDS = [
  'AGENT', 'ALPHA', 'ARROW', 'BEACON', 'BLACK', 'BLADE', 'BRAVO', 'CIPHER',
  'CLOAK', 'COBRA', 'DELTA', 'EAGLE', 'ECHO', 'FALCON', 'FLAME', 'FROST',
  'GHOST', 'GLIDER', 'GUARD', 'HAVEN', 'HAWK', 'HYDRA', 'INDEX', 'KEY',
  'KNIGHT', 'LASER', 'LEGION', 'LUNAR', 'MATRIX', 'NEXUS', 'OMEGA', 'ORACLE',
  'ORBIT', 'PHANTOM', 'PILOT', 'PRISM', 'PULSE', 'RADAR', 'RAVEN', 'RECON',
  'ROGUE', 'SABER', 'SCOUT', 'SHADOW', 'SHIELD', 'SIGNAL', 'SILVER', 'SIREN',
  'SOLAR', 'SPARTA', 'SPIDER', 'STEALTH', 'STORM', 'SWORD', 'TARGET', 'TEMPLE',
  'TITAN', 'TRACK', 'VALLEY', 'VAULT', 'VECTOR', 'VIPER', 'VORTEX', 'WOLF',
  'ZENITH', 'ZERO'
];

export const MEDIUM_WORDS = [
  'ALGORITHM', 'AMBASSADOR', 'ANONYMOUS', 'APPARATUS', 'ARCHETYPE', 'ARCHIVAL',
  'ARTILLERY', 'ASTRONOMY', 'ASYMMETRIC', 'AUTONOMOUS', 'BARRICADE', 'BLUEPRINT',
  'CAMOUFLAGE', 'CENTURION', 'CHRONICLE', 'CIRCUITRY', 'CLASSIFIED', 'COMMANDER',
  'CONVERGENCE', 'COORDINATE', 'CRYPTOGRAM', 'CYBERNETIC', 'DECIPHERER', 'DEFENSIVE',
  'DIPLOMACY', 'DISPATCH', 'ENCRYPTION', 'EXPEDITION', 'FORTIFICATION', 'FREQUENCY',
  'GUARDIAN', 'HEURISTIC', 'INSPECTOR', 'INTERCEPT', 'LABORATORY', 'LOGARITHM',
  'MANUSCRIPT', 'MICROSCOPE', 'MONARCHY', 'NAVIGATOR', 'OBSERVATORY', 'PARADIGM',
  'PERMUTATION', 'POLYBIUS', 'PROTOCOLS', 'QUICKSILVER', 'RESONANCE', 'SATELLITE',
  'SCRAMBLER', 'SECURITY', 'SEMAPHORE', 'SUBMARINE', 'SURVEILLANCE', 'SYMMETRY',
  'TELESCOPE', 'TERMINAL', 'TERRITORY', 'TRAJECTORY', 'TRANSPOSITION', 'VELOCITY'
];

export const TACTICAL_PHRASES = [
  'ATTACK AT DAWN',
  'DEFEND THE WALL',
  'SECRET ARCHIVE',
  'VENI VIDI VICI',
  'ET TU BRUTE',
  'FLEET EN ROUTE',
  'BLACK CHAMBER',
  'SPARTAN SCYTALE',
  'KRYPTOS VAULT',
  'OPERATION ECLIPSE',
  'DEVIATION DETECTED',
  'DECIPHER SUCCESS',
  'SIGNAL INTERCEPT',
  'MISSION CRITICAL',
  'SILENT NIGHT TRANSMISSION',
  'MIDNIGHT HORIZON',
  'THE EAGLE HAS LANDED',
  'CODE RED PROTOCOL',
  'PROJECT MANHATTAN',
  'BREAK THE CIPHER CODE',
  'ALL SHIPS DISPATCH',
  'GHOST IN THE MACHINE',
  'SECURE PERIMETER NOW',
  'DEEP COVER OPERATIVE',
  'RADIO SILENCE OBSERVED',
  'FORWARD OBSERVER LOCATED',
  'ENIGMA UNBROKEN TODAY',
  'RENDEZVOUS AT MIDNIGHT',
  'CODENAME NIGHTFALL',
  'SHADOW NETWORK ACTIVE',
  'QUANTUM ENTANGLEMENT',
  'KNOWLEDGE IS POWER',
  'DECIPHER THE CIPHER',
  'FORTUNE FAVORS THE BOLD',
  'SHIELDS AT MAXIMUM',
  'RADAR DETECTS CONTACT'
];

export const MASTER_PHRASE_POOL = [
  ...SHORT_WORDS,
  ...MEDIUM_WORDS,
  ...TACTICAL_PHRASES,
];

export function getPhraseForDifficulty(difficulty = 'easy') {
  const d = String(difficulty).toLowerCase();
  if (d === 'easy') {
    return Math.random() < 0.7
      ? SHORT_WORDS[Math.floor(Math.random() * SHORT_WORDS.length)]
      : TACTICAL_PHRASES[Math.floor(Math.random() * TACTICAL_PHRASES.length)];
  }
  if (d === 'medium') {
    return Math.random() < 0.6
      ? MEDIUM_WORDS[Math.floor(Math.random() * MEDIUM_WORDS.length)]
      : TACTICAL_PHRASES[Math.floor(Math.random() * TACTICAL_PHRASES.length)];
  }
  return MASTER_PHRASE_POOL[Math.floor(Math.random() * MASTER_PHRASE_POOL.length)];
}
